micronaut:
  application:
    name: auto_profile

datasources:
  default:
    url: ${JDBC_URL:`jdbc:h2:file:D:/Code/H2DB/auto_profile;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
    username: ${JDBC_USER:sa}
    password: ${JDBC_PASSWORD:""}
    schema-generate: CREATE_DROP
    dialect: H2
    driverClassName: ${JDBC_DRIVER:org.h2.Driver}

flyway:
  datasources:
    default:
      enabled: true
